#!/usr/bin/env bash
# installs Nginx on a server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install -y nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start