#!/usr/bin/env bash
# sets up a redirect page for a web server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
str="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;\n}"
sed -i "s@^}@$str@" /etc/nginx/sites-available/default
service nginx restart