#!/usr/bin/env bash
#Creating a bash script that creates an if statement
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    ((i++))
    done

    
