#!/usr/bin/env bash
#else if 
counter=0
while [ $counter -lt 10 ]
do (( counter+=1 ))
if  [ $counter -eq 4 ]
then echo "bad luck"
elif [ $counter -eq 8 ]
then echo "good luck"
else echo "Holberton School"
fi
done
